"use client";
import { useState,useEffect,useCallback, type ReactNode, type FormEvent } from 'react';
import { SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { LayoutDashboard,Users,Grid2X2,FileText,Wallet,Calculator,Settings,ChartColumn,Receipt,Plus,RefreshCw,Download,LogOut,Printer } from 'lucide-react';
import { money,schedule,today,addMonths } from '@/lib/finance';
import { authenticatedFetch,browserAuth } from '@/lib/supabase-browser';
import ClientFields from './client-fields';
import CurrencyInput from './currency-input';
type Client={id:string;name:string;document:string;phone:string;email:string;address:string;details?:string};
type Plot={id:string;block:string;number:string;area:string;price:number;status:string};
type Contract={id:string;client_id:string;plot_id:string;price:number;down_payment:number;count:number;annual_rate:string;first_due:string;created:string};
type Installment={id:string;contract_id:string;number:number;due:string;amount:number;paid_on:string|null;method:string|null};
type Data={clients:Client[];plots:Plot[];contracts:Contract[];installments:Installment[];settings:{company:string;document:string;phone:string}};
type Modal={kind:'client';item?:Client}|{kind:'plot';item?:Plot}|{kind:'sale'}|{kind:'pay';item:Installment}|{kind:'detail';item:Contract}|{kind:'receipt';item:Installment};
const navigation=[['dashboard','Dashboard',LayoutDashboard],['clients','Clientes',Users],['plots','Lotes',Grid2X2],['contracts','Vendas / Contratos',FileText],['installments','Parcelas',Receipt],['cash','Caixa',Wallet],['fiscal','Fiscal',FileText],['simulator','Simulador',Calculator],['reports','Relatórios',ChartColumn],['settings','Configurações',Settings]] as const;
type Page=typeof navigation[number][0];
const dateLabel=(date:string)=>date.split('-').reverse().join('/');
function Field({name,label,value='',type='text',required=false,min,max,step}:{name:string;label:string;value?:string|number;type?:string;required?:boolean;min?:string|number;max?:string|number;step?:string|number}){return <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type={type} defaultValue={value} required={required} min={min} max={max} step={step}/></div>}
function Choice({name,label,items,value,onChange,defaultValue}:{name:string;label:string;items:{value:string;label:string}[];value?:string;onChange?:(v:string)=>void;defaultValue?:string}){return <div className="field"><label htmlFor={name}>{label}</label><Select name={name} value={value} onValueChange={onChange} defaultValue={defaultValue} required><SelectTrigger id={name} className="select-control"><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select></div>}
function Grid({head,rows,empty='Nenhum registro encontrado.'}:{head:string[];rows:ReactNode[][];empty?:string}){return <div className="table-area"><Table><TableHeader><TableRow>{head.map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.length?rows.map((r,i)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={head.length}><div className="empty">{empty}</div></TableCell></TableRow>}</TableBody></Table></div>}
function Nav({page,change}:{page:Page;change:(p:Page)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{navigation.map(([key,label,Icon])=><SidebarMenuItem key={key}><SidebarMenuButton isActive={page===key} onClick={()=>{change(key);setOpenMobile(false)}} className="min-h-11 text-sm"><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}
function exportCsv(filename:string,head:string[],rows:(string|number)[][]){const safe=(v:string|number)=>{let s=String(v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const blob=new Blob(['\uFEFF'+[head,...rows].map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
export default function Workspace({name,emailAuth=false}:{name:string;emailAuth?:boolean}){
 const [page,setPage]=useState<Page>('dashboard');const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [modal,setModal]=useState<Modal|null>(null);const [saving,setSaving]=useState(false);const [formError,setFormError]=useState('');const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [salePlot,setSalePlot]=useState('');const [simulation,setSimulation]=useState<ReturnType<typeof schedule>|null>(null);const [simDown,setSimDown]=useState(0);const [rangeFrom,setRangeFrom]=useState(today().slice(0,7)+'-01');const [rangeTo,setRangeTo]=useState(today());
 const load=useCallback(async()=>{setLoading(true);try{const r=await (emailAuth?authenticatedFetch:fetch)('/api/data',{cache:'no-store'});const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os dados.')}finally{setLoading(false)}},[emailAuth]);
 useEffect(()=>{void load();const focus=()=>void load();window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus)},[load]);
 async function deleteClient(client:Client){if(saving)return;if(contracts.some(contract=>contract.client_id===client.id)){toast.error('Este cliente possui vendas ou contratos e não pode ser excluído.');return;}if(!window.confirm('Excluir o cliente '+client.name+'? Esta ação não pode ser desfeita.'))return;await save('deleteClient',{id:client.id});}
 function change(p:Page){setPage(p);setSearch('');setFilter('all')}
 function open(m:Modal){setModal(m);setFormError('');setSalePlot('')}
 async function save(action:string,payload:unknown){setSaving(true);setFormError('');try{const r=await (emailAuth?authenticatedFetch:fetch)('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:payload})});const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);setModal(null);toast.success(action==='deleteClient'?'Cliente excluído.':'Salvo com sucesso.');return true}catch(e){const msg=e instanceof Error?e.message:'Não foi possível salvar.';setFormError(msg);toast.error(msg);return false}finally{setSaving(false)}}
 useEffect(()=>{type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};const ctx=(document as Document&{modelContext?:Context}).modelContext;if(!ctx)return;const lifecycle=new AbortController();try{void Promise.resolve(ctx.registerTool({name:'navigate_lx_section',description:'Abre uma seção do LX Gestão sem alterar registros.',inputSchema:{type:'object',properties:{section:{type:'string',enum:navigation.map(n=>n[0])}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const p=(input as {section?:unknown})?.section;if(typeof p!=='string'||!navigation.some(n=>n[0]===p))throw new Error('Seção inválida');change(p as Page);return {section:p}}},{signal:lifecycle.signal})).catch(console.error)}catch(e){console.error(e)}return()=>lifecycle.abort()},[]);
 const clients=data?.clients??[];const plots=data?.plots??[];const contracts=data?.contracts??[];const installments=data?.installments??[];const day=today();
 const clientFor=(contractId:string)=>clients.find(c=>c.id===contracts.find(k=>k.id===contractId)?.client_id)?.name??'Cliente';
 const plotFor=(plotId:string)=>{const p=plots.find(p=>p.id===plotId);return p?`Quadra ${p.block} · Lote ${p.number}`:'Lote'};
 const status=(p:Installment)=>p.paid_on?'Pago':p.due<day?'Vencido':'Pendente';
 const badge=(s:string)=><span className={'badge '+(['Pago','Disponível'].includes(s)?'green':['Vencido','Vendido'].includes(s)?'red':'yellow')}>{s}</span>;
 const outstanding=installments.filter(p=>!p.paid_on);const overdue=outstanding.filter(p=>p.due<day);const paid=installments.filter(p=>p.paid_on);const sum=(items:Installment[])=>items.reduce((s,p)=>s+p.amount,0);
 const includes=(text:string)=>text.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'));
 const paymentRows=(items:Installment[],receipt=false)=>items.map(p=>[clientFor(p.contract_id),p.number===0?'Entrada':`${p.number}ª parcela`,dateLabel(receipt?p.paid_on!:p.due),money(p.amount),receipt?p.method:badge(status(p)),receipt?<button className="action-link" onClick={()=>open({kind:'receipt',item:p})}>Recibo</button>:p.paid_on?<button className="action-link" onClick={()=>open({kind:'receipt',item:p})}>Recibo</button>:<button className="action-link" onClick={()=>open({kind:'pay',item:p})}>Receber</button>]);
 const stats=<div className="stats"><article className="stat"><span>Lotes disponíveis</span><strong>{plots.filter(p=>p.status==='Disponível').length}</strong></article><article className="stat"><span>Clientes</span><strong>{clients.length}</strong></article><article className="stat"><span>Valor a receber</span><strong>{money(sum(outstanding))}</strong></article><article className="stat"><span>Recebido no mês</span><strong>{money(sum(paid.filter(p=>p.paid_on!.slice(0,7)===day.slice(0,7))))}</strong></article></div>;
 const paymentHead=['Cliente','Parcela','Vencimento','Valor','Status','Ação'];
 const methods=['Pix','Dinheiro','Transferência','Cartão','Boleto'].map(v=>({value:v,label:v}));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;const fd=new FormData(e.currentTarget);const s=(key:string)=>String(fd.get(key)??'').trim();const n=(key:string)=>Number(s(key));const c=(key:string)=>Math.round(n(key)*100);
  if(modal.kind==='client')await save('client',{id:modal.item?.id,name:s('name'),document:s('document').replace(/[^a-zA-Z0-9]/g,''),phone:s('phone'),email:s('email'),address:s('address'),details:JSON.parse(s('clientDetails')||'{}')});
  if(modal.kind==='plot')await save('plot',{id:modal.item?.id,block:s('block'),number:s('number'),area:s('area'),price:c('price'),status:s('status')});
  if(modal.kind==='sale')await save('sale',{clientId:s('clientId'),plotId:s('plotId'),price:c('price'),downPayment:c('downPayment'),count:n('count'),annualRate:n('annualRate'),firstDue:s('firstDue'),downPaid:fd.get('downPaid')==='on',downDate:s('downDate'),method:s('method')});
  if(modal.kind==='pay')await save('pay',{id:modal.item.id,paidOn:s('paidOn'),method:s('method')});
 }
 function simulate(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const n=(k:string)=>Number(fd.get(k));try{const down=Math.round(n('simEntry')*100);setSimulation(schedule(Math.round(n('simPrice')*100),down,n('simCount'),n('simRate'),String(fd.get('simDate'))));setSimDown(down);setFormError('')}catch(e){setFormError(e instanceof Error?e.message:'Revise os valores.');setSimulation(null)}}
 let content:ReactNode;
 if(page==='dashboard')content=<>{stats}<div className="two-col"><section className="panel"><div className="panel-head"><h2>Próximos vencimentos</h2><button className="action-link" onClick={()=>change('installments')}>Ver todas</button></div><Grid head={paymentHead} rows={paymentRows(outstanding.filter(p=>p.due>=day).slice(0,6))} empty="As próximas parcelas aparecerão aqui."/></section><section className="panel"><h2>Resumo de parcelas</h2>{[['Pagas',paid.length],['Pendentes',outstanding.length-overdue.length],['Vencidas',overdue.length]].map(([label,value])=><div className="row" key={label}><span>{label}</span><strong>{value}</strong></div>)}<p className="form-note">Valores incluem entradas e parcelas do financiamento.</p></section></div>{overdue.length>0&&<section className="panel"><div className="panel-head"><h2>Parcelas vencidas</h2><strong>{money(sum(overdue))}</strong></div><Grid head={paymentHead} rows={paymentRows(overdue.slice(0,6))}/></section>}<div className="toolbar-actions"><button className="secondary" onClick={()=>open({kind:'client'})}><Users size={18}/>Cadastrar cliente</button><button className="secondary" onClick={()=>open({kind:'plot'})}><Grid2X2 size={18}/>Cadastrar lote</button></div></>;
 else if(page==='clients')content=<section className="panel"><div className="filters"><input aria-label="Buscar clientes" placeholder="Buscar por nome, documento ou telefone" value={search} onChange={e=>setSearch(e.target.value)}/><button className="secondary" onClick={()=>exportCsv('clientes.csv',['Nome','Documento','Telefone','E-mail','Endereço'],clients.map(c=>[c.name,c.document,c.phone,c.email,c.address]))}><Download size={16}/>Exportar</button></div><Grid head={['Nome','CPF / CNPJ','Telefone','E-mail','Ação']} rows={clients.filter(c=>includes(c.name+' '+c.document+' '+c.phone)).map(c=>[c.name,c.document,c.phone||'—',c.email||'—',<div className="flex items-center gap-3"><button className="action-link" disabled={saving} onClick={()=>open({kind:'client',item:c})}>Editar</button><button className="action-link text-red-400" disabled={saving} aria-label={'Excluir cliente '+c.name} onClick={()=>void deleteClient(c)}>Excluir</button></div>])} empty="Cadastre seu primeiro cliente para começar."/></section>;
 else if(page==='plots')content=<section className="panel"><div className="filters"><input aria-label="Buscar lotes" placeholder="Buscar quadra ou lote" value={search} onChange={e=>setSearch(e.target.value)}/><Choice name="plotFilter" label="Status" value={filter} onChange={setFilter} items={['all','Disponível','Reservado','Vendido'].map(v=>({value:v,label:v==='all'?'Todos':v}))}/></div><Grid head={['Quadra','Lote','Área (m²)','Valor','Status','Ação']} rows={plots.filter(p=>includes(p.block+' '+p.number)&&(filter==='all'||p.status===filter)).map(p=>[p.block,p.number,p.area,money(p.price),badge(p.status),p.status==='Vendido'?'Vinculado à venda':<button className="action-link" onClick={()=>open({kind:'plot',item:p})}>Editar</button>])} empty="Cadastre os lotes disponíveis para venda."/></section>;
 else if(page==='contracts')content=<section className="panel"><div className="filters"><input aria-label="Buscar vendas" placeholder="Buscar cliente ou lote" value={search} onChange={e=>setSearch(e.target.value)}/></div><Grid head={['Cliente','Lote','Valor do lote','Entrada','Parcelas','Ação']} rows={contracts.filter(k=>includes((clients.find(c=>c.id===k.client_id)?.name??'')+' '+plotFor(k.plot_id))).map(k=>[clients.find(c=>c.id===k.client_id)?.name,plotFor(k.plot_id),money(k.price),money(k.down_payment),k.count,<button className="action-link" onClick={()=>open({kind:'detail',item:k})}>Ver venda</button>])} empty="As vendas registradas aparecerão aqui."/></section>;
 else if(page==='installments')content=<section className="panel"><div className="filters"><input aria-label="Buscar parcelas" placeholder="Buscar cliente" value={search} onChange={e=>setSearch(e.target.value)}/><Choice name="paymentFilter" label="Situação" value={filter} onChange={setFilter} items={['all','Pendente','Vencido','Pago'].map(v=>({value:v,label:v==='all'?'Todas':v}))}/></div><Grid head={paymentHead} rows={paymentRows(installments.filter(p=>includes(clientFor(p.contract_id))&&(filter==='all'||status(p)===filter)))}/></section>;
 else if(page==='cash'||page==='reports'){const received=paid.filter(p=>p.paid_on!>=rangeFrom&&p.paid_on!<=rangeTo);content=<><section className="panel"><div className="filters"><Field name="fromDate" label="De" value={rangeFrom} type="date"/><Field name="toDate" label="Até" value={rangeTo} type="date"/><button className="secondary" onClick={()=>{setRangeFrom((document.getElementById('fromDate') as HTMLInputElement).value);setRangeTo((document.getElementById('toDate') as HTMLInputElement).value)}}>Aplicar período</button><button className="secondary" onClick={()=>exportCsv('recebimentos.csv',['Cliente','Parcela','Pagamento','Valor (R$)','Forma'],received.map(p=>[clientFor(p.contract_id),p.number===0?'Entrada':String(p.number),dateLabel(p.paid_on!), (p.amount/100).toFixed(2).replace('.',','),p.method??'']))}><Download size={16}/>Exportar recebimentos</button></div><div className="row"><h2>Recebimentos no período</h2><strong>{money(sum(received))}</strong></div><Grid head={['Cliente','Parcela','Pagamento','Valor','Forma','Ação']} rows={paymentRows(received,true)} empty="Nenhum recebimento neste período."/></section>{page==='reports'&&<><section className="panel"><div className="panel-head"><h2>Inadimplência atual</h2><button className="secondary" onClick={()=>exportCsv('inadimplencia.csv',['Cliente','Parcela','Vencimento','Valor (R$)'],overdue.map(p=>[clientFor(p.contract_id),p.number===0?'Entrada':String(p.number),dateLabel(p.due),(p.amount/100).toFixed(2).replace('.',',')]))}>Exportar</button></div><div className="row"><span>Total vencido</span><strong>{money(sum(overdue))}</strong></div><Grid head={paymentHead} rows={paymentRows(overdue)}/></section><section className="panel"><h2>Vendas registradas</h2><div className="row"><span>Quantidade de vendas</span><strong>{contracts.length}</strong></div><div className="row"><span>Total dos lotes vendidos</span><strong>{money(contracts.reduce((s,k)=>s+k.price,0))}</strong></div><p className="form-note">Valores dos lotes sem os reajustes futuros das parcelas.</p></section></>}</>}
 else if(page==='simulator'){const annual=simulation?Array.from({length:Math.ceil(simulation.length/12)},(_,i)=>{const rows=simulation.slice(i*12,(i+1)*12);return [`${i+1}º ano`,rows.length,money(rows[0].amount),money(rows.reduce((s,p)=>s+p.amount,0))]}):[];content=<><section className="panel"><form onSubmit={simulate} className="form-grid"><CurrencyInput name="simPrice" label="Valor do lote (R$)" required/><CurrencyInput name="simEntry" label="Entrada (R$)" initialValue="0" required/><Field name="simCount" label="Quantidade de parcelas" type="number" min="1" max="600" value="120" required/><Field name="simRate" label="Correção anual (%)" type="number" min="0" max="100" step="0.01" value="0" required/><Field name="simDate" label="Primeiro vencimento" type="date" value={addMonths(day,1)} required/><div className="form-actions"><button className="primary">Calcular financiamento</button></div></form>{formError&&<p className="error">{formError}</p>}<p className="form-note">Reajuste fixo a cada 12 parcelas, a partir da 13ª. Sem juros adicionais, multa ou índice variável.</p></section>{simulation&&<><div className="stats"><article className="stat"><span>Parcela inicial</span><strong>{money(simulation[0].amount)}</strong></article><article className="stat"><span>Entrada</span><strong>{money(simDown)}</strong></article><article className="stat"><span>Total das parcelas</span><strong>{money(simulation.reduce((s,p)=>s+p.amount,0))}</strong></article><article className="stat"><span>Total com entrada</span><strong>{money(simDown+simulation.reduce((s,p)=>s+p.amount,0))}</strong></article></div><section className="panel"><div className="panel-head"><h2>Evolução anual</h2><button className="secondary" onClick={()=>exportCsv('simulacao.csv',['Parcela','Vencimento','Valor (R$)'],simulation.map(p=>[p.number,p.due,(p.amount/100).toFixed(2).replace('.',',')]))}>Exportar parcelas</button></div><Grid head={['Ano','Meses','Parcela inicial do ano','Total no ano']} rows={annual}/></section></>}</>}
 else if(page==='settings')content=<section className="panel"><h2>Dados da empresa</h2><form key={JSON.stringify(data?.settings)} className="form-grid" onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);await save('settings',{company:fd.get('company'),document:fd.get('companyDoc'),phone:fd.get('companyPhone')})}}><Field name="company" label="Nome da empresa" value={data?.settings.company} required/><Field name="companyDoc" label="CNPJ" value={data?.settings.document}/><Field name="companyPhone" label="Telefone" value={data?.settings.phone}/><div className="wide form-actions"><button className="primary" disabled={saving}>Salvar configurações</button></div></form><div className="row"><div><strong>Administrador</strong><p>{name}</p></div><span className="badge green">Acesso completo</span></div><p className="form-note">O acesso está restrito à sua conta do ChatGPT. Abra o mesmo endereço e entre com a mesma conta em outros dispositivos.</p><button className="secondary" onClick={()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download='lx-gestao-'+day+'.json';a.click();URL.revokeObjectURL(url)}}><Download size={16}/>Exportar cópia dos dados</button></section>;
 else content=<section className="panel"><h2>Integração fiscal pendente</h2><p className="form-note">Os recibos de pagamento estão disponíveis no Caixa e em Parcelas. Eles são comprovantes internos e não substituem documentos fiscais.</p><p className="form-note">A emissão fiscal precisa de configuração com o provedor e os dados da empresa.</p></section>;
 const title=navigation.find(n=>n[0]===page)?.[1];const canSell=clients.length>0&&plots.some(p=>p.status!=='Vendido');
 return <SidebarProvider><Toaster richColors/><Sidebar><SidebarHeader><div className="brand"><div className="brand-mark">LX</div><div><strong>LX Gestão</strong><span>Imobiliária</span></div></div><blockquote>“Mil poderão cair ao seu lado, dez mil à sua direita, mas nada o atingirá.”<small>Salmos 91:7</small></blockquote></SidebarHeader><SidebarContent><Nav page={page} change={change}/></SidebarContent><SidebarFooter><small>Área do administrador</small>{emailAuth?<button className="secondary" onClick={()=>void browserAuth().auth.signOut().then(({error})=>{if(error)toast.error("Não foi possível sair. Tente novamente.")})}><LogOut size={16}/>Sair</button>:<a href="/signout-with-chatgpt?return_to=%2F" target="_top" className="secondary"><LogOut size={16}/>Sair</a>}</SidebarFooter></Sidebar><SidebarInset><header className="topbar"><SidebarTrigger/><strong>{data?.settings.company??'LX Gestão Imobiliária'}</strong><span className="account">{name} · Administrador</span><button className="secondary" aria-label="Atualizar dados" title="Atualizar dados" onClick={()=>void load()} disabled={loading}><RefreshCw size={17}/></button></header><main className="workspace"><div className="page-head"><div><h1>{title}</h1><p>{page==='dashboard'?'Visão geral da operação':page==='cash'?'Entradas confirmadas de pagamentos':''}</p></div>{['dashboard','clients','plots','contracts'].includes(page)&&<button className="primary" disabled={!data} onClick={()=>open({kind:page==='clients'?'client':page==='plots'?'plot':'sale'})}><Plus size={18}/>{page==='clients'?'Novo cliente':page==='plots'?'Novo lote':'Nova venda'}</button>}</div>{error&&<div className="error" role="alert">{error} <button className="action-link" onClick={()=>void load()}>Tentar novamente</button></div>}{!data?<div className="panel empty">{loading?'Carregando seus dados…':'Seus dados não puderam ser carregados.'}</div>:content}<p className="footnote">LX Gestão Imobiliária · Datas no horário de Fortaleza · {loading?'Atualizando…':'Dados compartilhados entre seus dispositivos'}</p></main></SidebarInset>
 <Dialog open={!!modal} onOpenChange={v=>{if(!saving&&!v)setModal(null)}}><DialogContent className={modal?.kind==="client"?"dialog-body client-dialog":"dialog-body"} onInteractOutside={e=>{if(saving)e.preventDefault()}}><DialogHeader><DialogTitle>{modal?.kind==='client'?(modal.item?'Editar cliente':'Novo cliente'):modal?.kind==='plot'?(modal.item?'Editar lote':'Novo lote'):modal?.kind==='sale'?'Registrar venda':modal?.kind==='pay'?'Confirmar recebimento':modal?.kind==='detail'?'Detalhes da venda':'Recibo de pagamento'}</DialogTitle><DialogDescription>{modal?.kind==='sale'?'A venda vincula o lote ao cliente e gera as parcelas.':modal?.kind==='pay'?'Confirme os dados do pagamento recebido.':'LX Gestão Imobiliária'}</DialogDescription></DialogHeader>
 {modal&&['client','plot','sale','pay'].includes(modal.kind)&&<form onSubmit={submit}><div className="dialog-fields">
 {modal.kind==='client'&&<ClientFields key={modal.item?.id??'new'} initial={modal.item} history={modal.item?{sales:contracts.filter(c=>c.client_id===modal.item?.id).length,paid:sum(paid.filter(p=>contracts.some(c=>c.id===p.contract_id&&c.client_id===modal.item?.id))),pending:sum(outstanding.filter(p=>contracts.some(c=>c.id===p.contract_id&&c.client_id===modal.item?.id)))}:undefined}/>}
 {modal.kind==='plot'&&<div className="form-grid"><Field name="block" label="Quadra" value={modal.item?.block} required/><Field name="number" label="Número do lote" value={modal.item?.number} required/><Field name="area" label="Área (m²)" type="number" min="0.01" step="0.01" value={modal.item?.area} required/><CurrencyInput name="price" label="Valor (R$)" initialValue={modal.item?modal.item.price/100:''} required/><Choice name="status" label="Status" defaultValue={modal.item?.status??'Disponível'} items={['Disponível','Reservado'].map(v=>({value:v,label:v}))}/></div>}
 {modal.kind==='sale'&&(!canSell?<div className="info">Cadastre um cliente e um lote disponível antes de registrar uma venda.</div>:<><div className="form-grid"><Choice name="clientId" label="Cliente" items={clients.map(c=>({value:c.id,label:c.name}))}/><Choice name="plotId" label="Lote" value={salePlot} onChange={setSalePlot} items={plots.filter(p=>p.status!=='Vendido').map(p=>({value:p.id,label:plotFor(p.id)}))}/><CurrencyInput key={salePlot} name="price" label="Valor da venda (R$)" initialValue={salePlot?(plots.find(p=>p.id===salePlot)!.price/100):''} required/><CurrencyInput name="downPayment" label="Entrada (R$)" initialValue="0" required/><Field name="count" label="Quantidade de parcelas" type="number" min="1" max="600" value="120" required/><Field name="annualRate" label="Correção anual (%)" type="number" min="0" max="100" step="0.01" value="0" required/><Field name="firstDue" label="Primeiro vencimento" type="date" value={addMonths(day,1)} required/><Field name="downDate" label="Data da entrada" type="date" value={day} required/><Choice name="method" label="Forma de pagamento da entrada" defaultValue="Pix" items={methods}/><div className="field"><label htmlFor="downPaid">Entrada recebida?</label><div className="flex items-center gap-3"><Checkbox id="downPaid" name="downPaid"/><label htmlFor="downPaid">Sim, já recebi</label></div></div></div><p className="form-note">A entrada não recebida será registrada em aberto. A correção fixa começa na 13ª parcela e se repete a cada 12 meses.</p></>)}
 {modal.kind==='pay'&&<><div className="info"><strong>{clientFor(modal.item.contract_id)}</strong><p>{modal.item.number===0?'Entrada':`${modal.item.number}ª parcela`} · {money(modal.item.amount)} · Vencimento {dateLabel(modal.item.due)}</p></div><div className="form-grid"><Field name="paidOn" label="Data do recebimento" type="date" max={day} value={day} required/><Choice name="method" label="Forma de pagamento" defaultValue="Pix" items={methods}/></div></>}
 {formError&&<div className="error" role="alert">{formError}</div>}</div><div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>setModal(null)}>Cancelar</button><button type="submit" className="primary" disabled={saving||(modal.kind==='sale'&&!canSell)}>{saving?'Salvando…':modal.kind==='pay'?'Confirmar recebimento':modal.kind==='sale'?'Registrar venda':'Salvar'}</button></div></form>}
 {modal?.kind==='detail'&&<><p><strong>{clients.find(c=>c.id===modal.item.client_id)?.name}</strong></p><p>{plotFor(modal.item.plot_id)}</p><div className="row"><span>Valor do lote</span><strong>{money(modal.item.price)}</strong></div><div className="row"><span>Entrada</span><strong>{money(modal.item.down_payment)}</strong></div><div className="row"><span>Correção anual fixa</span><strong>{Number(modal.item.annual_rate).toLocaleString('pt-BR')}%</strong></div><div className="row"><span>Total com correção</span><strong>{money(sum(installments.filter(p=>p.contract_id===modal.item.id)))}</strong></div><div className="row"><span>Saldo a receber</span><strong>{money(sum(outstanding.filter(p=>p.contract_id===modal.item.id)))}</strong></div><p className="form-note">Registro gerencial da venda. A emissão de documento contratual não está integrada.</p><button className="secondary" onClick={()=>exportCsv('parcelas-venda.csv',['Parcela','Vencimento','Valor (R$)','Pagamento'],installments.filter(p=>p.contract_id===modal.item.id).map(p=>[p.number===0?'Entrada':p.number,p.due,(p.amount/100).toFixed(2).replace('.',','),p.paid_on??'Em aberto']))}><Download size={16}/>Exportar parcelas</button></>}
 {modal?.kind==='receipt'&&<div className="receipt"><h2>{data?.settings.company}</h2>{data?.settings.document&&<p>CNPJ: {data.settings.document}</p>}<p>Recebemos de <strong>{clientFor(modal.item.contract_id)}</strong> o valor de <strong>{money(modal.item.amount)}</strong>, referente a {modal.item.number===0?'entrada':`${modal.item.number}ª parcela`} de {plotFor(contracts.find(c=>c.id===modal.item.contract_id)?.plot_id??'')}.</p><p className="form-note">Pagamento: {dateLabel(modal.item.paid_on!)} · {modal.item.method}</p><p className="form-note">Identificação: {modal.item.id}</p><p className="form-note">Comprovante interno de recebimento.</p><button className="secondary" onClick={()=>window.print()}><Printer size={16}/>Imprimir / salvar PDF</button></div>}
 </DialogContent></Dialog></SidebarProvider>
}


